variable "name" {
  description = "Project name as it appears in the Supabase dashboard, e.g. \"tomame-prod\"."
  type        = string
}

variable "organization_id" {
  description = "Supabase organization the project belongs to."
  type        = string
}

variable "region" {
  description = <<-EOT
    Supabase region. Immutable: Supabase cannot move a project, so Terraform
    implements a change here as destroy-then-create, which drops the database.
    The lifecycle block in main.tf refuses to do that silently.
  EOT
  type        = string
}

variable "database_password" {
  description = "Postgres superuser password. Generated by the caller, never typed by a human."
  type        = string
  sensitive   = true
}

variable "instance_size" {
  description = "Compute add-on size, or null for the organization default."
  type        = string
  default     = null
}

variable "site_url" {
  description = <<-EOT
    Canonical origin of the app. Supabase Auth builds every emailed link —
    confirmation, password reset, magic link — against this value, so if it is
    wrong the links in real customer email point somewhere wrong.
  EOT
  type        = string
}

variable "additional_redirect_urls" {
  description = <<-EOT
    Extra origins Auth will redirect back to after a flow completes. Vercel
    preview deployments each get a fresh hostname, so a wildcard entry is the
    only practical way to make auth work on previews.
  EOT
  type        = list(string)
  default     = []
}

variable "jwt_expiry_seconds" {
  description = "Access-token lifetime. One hour is the Supabase default."
  type        = number
  default     = 3600

  validation {
    condition     = var.jwt_expiry_seconds >= 300 && var.jwt_expiry_seconds <= 604800
    error_message = "jwt_expiry_seconds must be between 300 (5 minutes) and 604800 (1 week)."
  }
}

variable "enable_signup" {
  description = "Whether self-service signup is open. Tomame's customers self-register, so this is true."
  type        = bool
  default     = true
}

variable "db_schema" {
  description = "Schemas PostgREST exposes. Only \"public\" — RLS policies are written against public tables."
  type        = string
  default     = "public"
}

variable "max_rows" {
  description = <<-EOT
    Hard cap on rows a single PostgREST request may return. It is a safety net,
    not a page size: without it a missing filter on the admin orders view returns
    the entire table.
  EOT
  type        = number
  default     = 1000
}

variable "extra_auth_settings" {
  description = <<-EOT
    Merged over the auth settings this module builds, for fields it does not model.
    An escape hatch: the Supabase Management API accepts more settings than are
    worth giving named variables, and this avoids forking the module to set one.
  EOT
  type        = map(any)
  default     = {}
}
