import { TomameCategory } from "./tomame_category";

// Shein category strings mapped to Tomame categories (shippable items only)
// Shein uses breadcrumb paths and cat_name fields for categorization
export const SHEIN_CATEGORY_MAP = new Map<string, TomameCategory>([
  // Women's Clothing
  ["Women", TomameCategory.CLOTHING_WOMEN],
  ["Women Clothing", TomameCategory.CLOTHING_WOMEN],
  ["Women's Clothing", TomameCategory.CLOTHING_WOMEN],
  ["Dresses", TomameCategory.CLOTHING_WOMEN],
  ["Women Dresses", TomameCategory.CLOTHING_WOMEN],
  ["Tops", TomameCategory.CLOTHING_WOMEN],
  ["Women Tops", TomameCategory.CLOTHING_WOMEN],
  ["T-Shirts", TomameCategory.CLOTHING_WOMEN],
  ["Blouses", TomameCategory.CLOTHING_WOMEN],
  ["Bodysuits", TomameCategory.CLOTHING_WOMEN],
  ["Sweaters", TomameCategory.CLOTHING_WOMEN],
  ["Hoodies & Sweatshirts", TomameCategory.CLOTHING_WOMEN],
  ["Jackets & Coats", TomameCategory.CLOTHING_WOMEN],
  ["Outerwear", TomameCategory.CLOTHING_WOMEN],
  ["Bottoms", TomameCategory.CLOTHING_WOMEN],
  ["Women Bottoms", TomameCategory.CLOTHING_WOMEN],
  ["Pants", TomameCategory.CLOTHING_WOMEN],
  ["Jeans", TomameCategory.CLOTHING_WOMEN],
  ["Skirts", TomameCategory.CLOTHING_WOMEN],
  ["Shorts", TomameCategory.CLOTHING_WOMEN],
  ["Jumpsuits & Rompers", TomameCategory.CLOTHING_WOMEN],
  ["Co-ords", TomameCategory.CLOTHING_WOMEN],
  ["Two-piece Outfits", TomameCategory.CLOTHING_WOMEN],
  ["Matching Sets", TomameCategory.CLOTHING_WOMEN],
  ["Swimwear", TomameCategory.CLOTHING_WOMEN],
  ["Bikinis", TomameCategory.CLOTHING_WOMEN],
  ["Lingerie", TomameCategory.CLOTHING_WOMEN],
  ["Loungewear", TomameCategory.CLOTHING_WOMEN],
  ["Sleepwear", TomameCategory.CLOTHING_WOMEN],
  ["Plus Size", TomameCategory.CLOTHING_WOMEN],
  ["Curve + Plus", TomameCategory.CLOTHING_WOMEN],
  ["Maternity", TomameCategory.CLOTHING_WOMEN],
  ["Activewear", TomameCategory.CLOTHING_WOMEN],
  ["Women Activewear", TomameCategory.CLOTHING_WOMEN],

  // Men's Clothing
  ["Men", TomameCategory.CLOTHING_MEN],
  ["Men Clothing", TomameCategory.CLOTHING_MEN],
  ["Men's Clothing", TomameCategory.CLOTHING_MEN],
  ["Men Tops", TomameCategory.CLOTHING_MEN],
  ["Men T-Shirts", TomameCategory.CLOTHING_MEN],
  ["Men Shirts", TomameCategory.CLOTHING_MEN],
  ["Men Bottoms", TomameCategory.CLOTHING_MEN],
  ["Men Pants", TomameCategory.CLOTHING_MEN],
  ["Men Jeans", TomameCategory.CLOTHING_MEN],
  ["Men Shorts", TomameCategory.CLOTHING_MEN],
  ["Men Jackets & Coats", TomameCategory.CLOTHING_MEN],
  ["Men Outerwear", TomameCategory.CLOTHING_MEN],
  ["Men Hoodies & Sweatshirts", TomameCategory.CLOTHING_MEN],
  ["Men Sweaters", TomameCategory.CLOTHING_MEN],
  ["Men Suits & Blazers", TomameCategory.CLOTHING_MEN],
  ["Men Underwear", TomameCategory.CLOTHING_MEN],
  ["Men Sleepwear", TomameCategory.CLOTHING_MEN],
  ["Men Activewear", TomameCategory.CLOTHING_MEN],

  // Kids' Clothing
  ["Kids", TomameCategory.CLOTHING_KIDS],
  ["Kids Clothing", TomameCategory.CLOTHING_KIDS],
  ["Girls", TomameCategory.CLOTHING_KIDS],
  ["Girls Clothing", TomameCategory.CLOTHING_KIDS],
  ["Boys", TomameCategory.CLOTHING_KIDS],
  ["Boys Clothing", TomameCategory.CLOTHING_KIDS],
  ["Baby", TomameCategory.BABY],
  ["Baby Girl", TomameCategory.BABY],
  ["Baby Boy", TomameCategory.BABY],
  ["Toddler", TomameCategory.BABY],
  ["Toddler Girl", TomameCategory.BABY],
  ["Toddler Boy", TomameCategory.BABY],

  // Shoes
  ["Shoes", TomameCategory.SHOES_WOMEN],
  ["Women Shoes", TomameCategory.SHOES_WOMEN],
  ["Women's Shoes", TomameCategory.SHOES_WOMEN],
  ["Heels", TomameCategory.SHOES_WOMEN],
  ["Sandals", TomameCategory.SHOES_WOMEN],
  ["Boots", TomameCategory.SHOES_WOMEN],
  ["Flats", TomameCategory.SHOES_WOMEN],
  ["Sneakers", TomameCategory.SHOES_WOMEN],
  ["Slippers", TomameCategory.SHOES_WOMEN],
  ["Men Shoes", TomameCategory.SHOES_MEN],
  ["Men's Shoes", TomameCategory.SHOES_MEN],
  ["Men Sneakers", TomameCategory.SHOES_MEN],
  ["Men Sandals", TomameCategory.SHOES_MEN],
  ["Men Boots", TomameCategory.SHOES_MEN],
  ["Men Slippers", TomameCategory.SHOES_MEN],
  ["Kids Shoes", TomameCategory.SHOES_KIDS],
  ["Girls Shoes", TomameCategory.SHOES_KIDS],
  ["Boys Shoes", TomameCategory.SHOES_KIDS],

  // Bags & Accessories
  ["Bags", TomameCategory.HANDBAGS],
  ["Women Bags", TomameCategory.HANDBAGS],
  ["Handbags", TomameCategory.HANDBAGS],
  ["Crossbody Bags", TomameCategory.HANDBAGS],
  ["Shoulder Bags", TomameCategory.HANDBAGS],
  ["Tote Bags", TomameCategory.HANDBAGS],
  ["Backpacks", TomameCategory.HANDBAGS],
  ["Wallets", TomameCategory.HANDBAGS],
  ["Clutches", TomameCategory.HANDBAGS],
  ["Men Bags", TomameCategory.HANDBAGS],
  ["Travel Bags", TomameCategory.LUGGAGE],
  ["Luggage", TomameCategory.LUGGAGE],
  ["Suitcases", TomameCategory.LUGGAGE],

  // Accessories
  ["Accessories", TomameCategory.FASHION_ACCESSORIES],
  ["Women Accessories", TomameCategory.FASHION_ACCESSORIES],
  ["Men Accessories", TomameCategory.FASHION_ACCESSORIES],
  ["Hats", TomameCategory.FASHION_ACCESSORIES],
  ["Scarves", TomameCategory.FASHION_ACCESSORIES],
  ["Belts", TomameCategory.FASHION_ACCESSORIES],
  ["Sunglasses", TomameCategory.FASHION_ACCESSORIES],
  ["Gloves", TomameCategory.FASHION_ACCESSORIES],
  ["Hair Accessories", TomameCategory.FASHION_ACCESSORIES],
  ["Socks & Hosiery", TomameCategory.FASHION_ACCESSORIES],

  // Jewelry
  ["Jewelry", TomameCategory.JEWELRY],
  ["Necklaces", TomameCategory.JEWELRY],
  ["Earrings", TomameCategory.JEWELRY],
  ["Rings", TomameCategory.JEWELRY],
  ["Bracelets", TomameCategory.JEWELRY],
  ["Anklets", TomameCategory.JEWELRY],
  ["Body Jewelry", TomameCategory.JEWELRY],

  // Watches
  ["Watches", TomameCategory.WATCHES],
  ["Women Watches", TomameCategory.WATCHES],
  ["Men Watches", TomameCategory.WATCHES],

  // Beauty
  ["Beauty", TomameCategory.BEAUTY],
  ["Beauty & Health", TomameCategory.BEAUTY],
  ["Skin Care", TomameCategory.SKINCARE],
  ["Skincare", TomameCategory.SKINCARE],
  ["Face", TomameCategory.SKINCARE],
  ["Makeup", TomameCategory.MAKEUP],
  ["Eyes Makeup", TomameCategory.MAKEUP],
  ["Lip Makeup", TomameCategory.MAKEUP],
  ["Face Makeup", TomameCategory.MAKEUP],
  ["Nail Art", TomameCategory.MAKEUP],
  ["Nails", TomameCategory.MAKEUP],
  ["Hair Care", TomameCategory.HAIRCARE],
  ["Hair Tools", TomameCategory.HAIRCARE],
  ["Wigs & Hair Pieces", TomameCategory.HAIRCARE],
  ["Fragrance", TomameCategory.FRAGRANCE],
  ["Perfume", TomameCategory.FRAGRANCE],
  ["Bath & Body", TomameCategory.PERSONAL_CARE],
  ["Personal Care", TomameCategory.PERSONAL_CARE],
  ["Beauty Tools", TomameCategory.BEAUTY],
  ["Makeup Tools", TomameCategory.BEAUTY],

  // Home & Living
  ["Home", TomameCategory.HOME_KITCHEN],
  ["Home & Living", TomameCategory.HOME_KITCHEN],
  ["Home Decor", TomameCategory.HOME_KITCHEN],
  ["Wall Decor", TomameCategory.HOME_KITCHEN],
  ["Storage & Organization", TomameCategory.HOME_KITCHEN],
  ["Kitchen", TomameCategory.KITCHEN_DINING],
  ["Kitchen & Dining", TomameCategory.KITCHEN_DINING],
  ["Kitchenware", TomameCategory.KITCHEN_DINING],
  ["Drinkware", TomameCategory.KITCHEN_DINING],
  ["Dining", TomameCategory.KITCHEN_DINING],
  ["Bedding", TomameCategory.BEDDING],
  ["Bed Linen", TomameCategory.BEDDING],
  ["Blankets & Throws", TomameCategory.BEDDING],
  ["Pillows", TomameCategory.BEDDING],
  ["Bath", TomameCategory.BATH],
  ["Bathroom", TomameCategory.BATH],
  ["Towels", TomameCategory.BATH],
  ["Lighting", TomameCategory.LIGHTING],
  ["Lamps", TomameCategory.LIGHTING],
  ["Candles & Holders", TomameCategory.HOME_KITCHEN],
  ["Furniture", TomameCategory.FURNITURE],
  ["Rugs & Carpets", TomameCategory.HOME_KITCHEN],
  ["Curtains", TomameCategory.HOME_KITCHEN],
  ["Garden", TomameCategory.GARDEN_OUTDOOR],
  ["Outdoor", TomameCategory.GARDEN_OUTDOOR],

  // Electronics & Accessories
  ["Electronics", TomameCategory.ELECTRONICS],
  ["Phone Cases", TomameCategory.CELL_PHONES],
  ["Phone Accessories", TomameCategory.CELL_PHONES],
  ["Earphones & Headphones", TomameCategory.HEADPHONES],
  ["Laptop Accessories", TomameCategory.COMPUTERS],
  ["Tablet Accessories", TomameCategory.COMPUTERS],
  ["Smart Watches", TomameCategory.WEARABLE_TECHNOLOGY],

  // Stationery & Office
  ["Stationery", TomameCategory.OFFICE_PRODUCTS],
  ["Office Supplies", TomameCategory.OFFICE_PRODUCTS],
  ["School Supplies", TomameCategory.SCHOOL_SUPPLIES],

  // Pet Supplies
  ["Pet Supplies", TomameCategory.PET_SUPPLIES],
  ["Pets", TomameCategory.PET_SUPPLIES],
  ["Dog Supplies", TomameCategory.PET_SUPPLIES],
  ["Cat Supplies", TomameCategory.PET_SUPPLIES],

  // Sports & Fitness
  ["Sports", TomameCategory.SPORTS_OUTDOORS],
  ["Sports & Outdoors", TomameCategory.SPORTS_OUTDOORS],
  ["Fitness", TomameCategory.EXERCISE_FITNESS],
  ["Yoga", TomameCategory.EXERCISE_FITNESS],
  ["Sportswear", TomameCategory.SPORTS_OUTDOORS],

  // Toys & Games
  ["Toys", TomameCategory.TOYS_GAMES],
  ["Toys & Games", TomameCategory.TOYS_GAMES],

  // Arts & Crafts
  ["Arts & Crafts", TomameCategory.ARTS_CRAFTS],
  ["DIY", TomameCategory.ARTS_CRAFTS],
  ["Sewing", TomameCategory.ARTS_CRAFTS],
  ["Fabric", TomameCategory.FABRIC],
]);
