/**
 * Reads `npx supabase status` output and writes .env.local
 * with the local Supabase credentials.
 */
import { execSync } from "child_process";
import { writeFileSync, existsSync, copyFileSync } from "fs";
import { resolve } from "path";

const PROJECT_ROOT = resolve(__dirname, "..");
const ENV_FILE = resolve(PROJECT_ROOT, ".env");

function getStatusValue(output: string, key: string): string {
  const regex = new RegExp(`^\\s*${key}:\\s*(.+)$`, "m");
  const match = output.match(regex);
  return match?.[1]?.trim() ?? "";
}

function main() {
  console.log("Reading local Supabase credentials...\n");

  let status: string;
  try {
    status = execSync("npx supabase status", {
      cwd: PROJECT_ROOT,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
  } catch (err: unknown) {
    const execErr = err as { stderr?: string };
    console.error(
      "Failed to get Supabase status. Is Supabase running?\n" +
        "  Run: npm run supabase:start\n\n" +
        (execErr.stderr ?? "")
    );
    process.exit(1);
  }

  const apiUrl = getStatusValue(status, "API URL");
  const anonKey = getStatusValue(status, "anon key");
  const serviceRoleKey = getStatusValue(status, "service_role key");
  const studioUrl = getStatusValue(status, "Studio URL");
  const inbucketUrl = getStatusValue(status, "Inbucket URL");
  const dbUrl = getStatusValue(status, "DB URL");

  if (!apiUrl || !anonKey || !serviceRoleKey) {
    console.error("Could not parse Supabase status output:\n", status);
    process.exit(1);
  }

  // Back up existing .env.local
  if (existsSync(ENV_FILE)) {
    const backup = `${ENV_FILE}.backup.${Date.now()}`;
    copyFileSync(ENV_FILE, backup);
    console.log(`Backed up existing .env.local → ${backup}\n`);
  }

  const envContent = `# ===========================================
# Local Supabase (auto-generated by npm run supabase:env)
# ===========================================

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${anonKey}
SUPABASE_SECRET_KEY=${serviceRoleKey}

# Paystack (replace with your test keys)
PAYSTACK_SECRET_KEY=sk_test_xxxxx
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=pk_test_xxxxx

# Resend
RESEND_API_KEY=re_xxxxx
RESEND_FROM_EMAIL=Tomame <no-reply@tomame.com>

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

  writeFileSync(ENV_FILE, envContent, "utf-8");

  console.log(".env.local written with local Supabase credentials.\n");
  console.log(`  API URL:   ${apiUrl}`);
  console.log(`  Studio:    ${studioUrl}`);
  console.log(`  Inbucket:  ${inbucketUrl}`);
  console.log(`  DB URL:    ${dbUrl}`);
  console.log();
}

main();
